### ISSUE TITLE
Does pywws work with Davis Vantage Pro 2?

### ISSUE THREAD

**Issue by rjcorley** [jim-easterbrook/pywws#20]
I'm trying to get my Raspberry Pi running pywws to work with my Vantage Pro 2 with the USB data logger installed.  When I run pywws.TestWeatherStation I get:

python -m pywws.TestWeatherStation
07:04:13:pywws.Logger:pywws version 14.12.0
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/pywws/TestWeatherStation.py", lin                                 e 180, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pywws/TestWeatherStation.py", lin                                 e 115, in main
    ws = WeatherStation.weather_station()
  File "/usr/local/lib/python2.7/dist-packages/pywws/WeatherStation.py", line 40                                 5, in __init__
    self.cusb = CUSBDrive()
  File "/usr/local/lib/python2.7/dist-packages/pywws/WeatherStation.py", line 25                                 2, in __init__
    self.dev = USBDevice(0x1941, 0x8021)
  File "/usr/local/lib/python2.7/dist-packages/pywws/device_pyusb.py", line 99,                                  in __init__
    raise IOError("Weather station device not found")
IOError: Weather station device not found
Exception AttributeError: "'USBDevice' object has no attribute 'devh'" in <bound                                  method USBDevice.__del__ of <pywws.device_pyusb.USBDevice object at 0xb689fc50>    

When I run lsusb I see the Data Logger interface:
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp.
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp.
Bus 001 Device 004: ID 154b:007a PNY
Bus 001 Device 005: ID 10c4:ea61 Cygnal Integrated Products, Inc. CP210x UART Bridge
Bus 001 Device 006: ID 148f:5370 Ralink Technology, Corp. RT5370 Wireless Adapter

The weather station is the CP210x UART Bridge

Any suggestion?

**Comment by jim-easterbrook** [comment]
From the README: "any model that is supplied with the EasyWeather Windows software is compatible".
